name: Ruby CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read

jobs:
  test:
    name: Ruby ${{ matrix.ruby }} / Rails ${{ matrix.rails }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Roughly pulled from https://www.fastruby.io/blog/ruby/rails/versions/compatibility-table.html
        include:
          # - { rails: "6.0", ruby: "2.5" }
          # - { rails: "6.0", ruby: "2.6" }
          # - { rails: "6.0", ruby: "2.7" }
          - { rails: "6.0", ruby: "3.0" }

          # - { rails: "6.1", ruby: "2.5" }
          # - { rails: "6.1", ruby: "2.6" }
          # - { rails: "6.1", ruby: "2.7" }
          - { rails: "6.1", ruby: "3.0" }

          # - { rails: "7.0", ruby: "2.7" }
          - { rails: "7.0", ruby: "3.0" }
          - { rails: "7.0", ruby: "3.1" }

          # - { rails: "7.1", ruby: "2.7" }
          - { rails: "7.1", ruby: "3.0" }
          - { rails: "7.1", ruby: "3.1" }
          - { rails: "7.1", ruby: "3.2" }

          - { rails: "7.2", ruby: "3.1" }
          - { rails: "7.2", ruby: "3.2" }
          - { rails: "7.2", ruby: "3.3" }

          - { rails: "8.0", ruby: "3.2" }
          - { rails: "8.0", ruby: "3.3" }
          - { rails: "8.0", ruby: "3.4" }
          - { rails: "8.0", ruby: "3.5.0-preview1" }
    env:
      RAILS_VERSION: "~> ${{ matrix.rails }}.0"

    steps:
    - uses: actions/checkout@v4
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
        cache-version: ruby-${{ matrix.ruby }}:rails-${{ matrix.rails }}
    - name: Run tests
      run: bundle exec rake
